### ISSUE TITLE
Web canvaskit renderer version doesn't work

### ISSUE THREAD

**Issue by fe-data** [juliansteenbakker/mobile_scanner#708] opened 2023-08-04 11:51 UTC
Running a web based version with `flutter build web --web-renderer canvaskit` doesn't work.

Error is: `Permission denied NoSuchMethodError: method not found: "BrowserMultiFormatReader" on null`.

It works fine with `flutter build web --web-renderer html`, but I need the canvaskit renderer.

Using flutter 3.10.6 and mobile_scanner 3.3.0. Issue may be related to #222

**Code snippet** 
```dart
late final MobileScannerController _controller = MobileScannerController(formats: [BarcodeFormat.qrCode]);

...
...
MobileScanner( 
                  controller: _controller,
                  errorBuilder: (context, error, child) {
                    return CameraErrorWidget(error: error);
                  },
                  onDetect: _onDetect,
                ))
...
...
```

**Comment by PawlikMichal25** [comment] 2023-08-04 19:09
Seems to be a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/622

**Comment by navaronbracke** [comment] 2023-10-12 19:24
As mentioned, this is a duplicate of #622 , which has since been fixed.

**Closed by navaronbracke** 2023-10-12 19:24 UTC
Labels: web
