### ISSUE TITLE
After Updating Mac M1 => Sequoia and xCode 16 

### ISSUE THREAD

**Issue by MBilalMurtaZa** [juliansteenbakker/mobile_scanner#1190] opened 2024-09-24 08:12 UTC
[!] CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 5.4.2, which depends on
      Firebase/Firestore (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseFirestore (~> 11.0.0) was resolved to 11.0.0, which depends on
          FirebaseFirestoreInternal (= 11.0.0) was resolved to 11.0.0, which depends on
            nanopb (~> 3.30910.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        MLKitBarcodeScanning (~> 5.0.0) was resolved to 5.0.0, which depends on
          MLKitCommon (~> 11.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1) was resolved to 9.4.1, which depends on
              nanopb (< 2.30911.0, >= 2.30908.0)

**Comment by navaronbracke** [comment] 2024-09-26 19:58
This is a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1165

And as far as I know, the Firebase plugins have some issues with XCode 16 at the moment.

**Closed by navaronbracke** 2024-09-26 19:58 UTC
