### ISSUE TITLE
Error on android 

### ISSUE THREAD

**Issue by harryandroiddev** [juliansteenbakker/mobile_scanner#934] opened 2024-01-17 10:32 UTC
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mobile_scanner:compileDebugJavaWithJavac'.
> error: invalid source release: 17

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by ArturDias13** [comment] 2024-01-17 12:35
Rollback your mobile scanner version on pubspec.yaml to 3.5.5 (remember to remove ^ symbol)

`mobile_scanner: 3.5.5`

**Comment by navaronbracke** [comment] 2024-01-18 10:18
Duplicate of #922

**Closed by navaronbracke** 2024-01-18 10:18 UTC
