### ISSUE TITLE
Camera Preview Freezes upon Reopening MobileScanner Widget

### ISSUE THREAD

**Issue by jeremyLACLICK** [juliansteenbakker/mobile_scanner#976] opened 2024-03-06 12:12 UTC
Hi there,

Thank you for the great package! Recently, the camera preview freezes whenever I open the widget containing it for the second time. I have the same issue when running my web app in the debugger and after deploying it. I also have this issue when running the project provided in the 'example' folder of this repository. 

It is possible that the problem is due to an incompatibility with the most recent Dart update? 

I noticed that when I pass the controller as a parameter of the Widget that contains the MobileScanner, the camera preview no longer freezes when it is opened for the second time. Does the issue then relate to the way I am using the MobileScannerController?

[Test.txt](https://github.com/juliansteenbakker/mobile_scanner/files/14509803/Test.txt)

Best,
Jeremy

**Comment by navaronbracke** [comment] 2024-03-06 13:01
> I noticed that when I pass the controller as a parameter of the Widget that contains the MobileScanner, 
> the camera >preview no longer freezes when it is opened for the second time.

That sounds like the bug with the lifecycle management. Are you using version 4.0.x ?
You could try validating with the new beta, `5.0.0-beta.1`, which removes internal lifecycle management of the controller from the MobileScanner widget. That bug caused issues with widget tree reparenting, so we removed the lifecycle management from the plugin. You can use the updated example app from this beta version to validate. It also includes updates to the web support, using the new JS interop that was introduced with Dart 3.3

**Comment by jeremyLACLICK** [comment] 2024-03-07 07:47
Hi there,

I am indeed using version 4.0.1. I will give the beta version a try, although I can see it is incompatible with another one of my project's dependencies.

Thank you in any case for the help!

**Comment by lavinov-mercury** [comment] 2024-03-11 12:09
Seems like it's related not to lib changes, but to the Flutter upgrade. It started reproducing with 3.19.0 stable version, no matter which version of the lib is used (tried 5.0.0 as well). With 3.16.9 the issue is not reproducible for me.

**Comment by jeremyLACLICK** [comment] 2024-03-18 09:20
Thanks!

**Comment by romawizard** [comment] 2024-03-29 11:56
Any updates?

**Comment by navaronbracke** [comment] 2024-03-29 12:52
> I noticed that when I pass the controller as a parameter of the Widget that contains the MobileScanner, the camera preview no longer freezes when it is opened for the second time.

For anyone asking for updated: You should provide a `MobileScannerController` to the `MobileScanner` widget. 
This is the recommended way to do things and will be the only way to use the widget starting from version 5.0.0

**Comment by wkok** [comment] 2024-04-04 15:46
> > I noticed that when I pass the controller as a parameter of the Widget that contains the MobileScanner, the camera preview no longer freezes when it is opened for the second time.
> 
> For anyone asking for updates: You should provide a `MobileScannerController` to the `MobileScanner` widget. This is the recommended way to do things and will be the only way to use the widget starting from version 5.0.0

Hello,

Providing a `MobileScannerController` to the `MobileScanner` widget works to not have the camera preview freeze when it's opened the second time, however, the actual scanning of a barcode only works on the first attempt of the preview being opened, not the second etc.. until I refresh the browser, the barcode scans the first time but then not again on subsequent attempts.

**Comment by fg0611** [comment] 2024-04-05 19:49
Hi I have a similar issue with Flutter Web. The camera stops/freezes after mounting the same widget that uses `MobileScanner widget`. I'm using the controller just like in the example for package version `5.0.0-beta.2` with everything else using WidgetsBindingObserver, StreamSubscription and the function called didChangeAppLifecycleState as is.

With package version 5.0.0-beta.2 I'm using flutter  3.19.5, dart 3.3.3. 

Another thing that I'm getting browser message `library@0.19.1:15 Trying to play video that is already playing.` could this be related to the freezing?

Also I had same problem using package version 4.0.1 and 3.5.7 with flutter older version and dart older version too.

**Comment by joymyr** [comment] 2024-04-08 13:59
Im having the same issue as @fg0611, and it seems like web support was broken in 5.0.0-beta.1

**Comment by joymyr** [comment] 2024-04-08 20:02
No, I'm getting `Trying to play video that is already playing` even the first time calling start

**Comment by navaronbracke** [comment] 2024-04-08 20:20
> No, I'm getting `Trying to play video that is already playing` even the first time calling start

Then what did you mean by `it seems like web support was broken in 5.0.0-beta.1` ? The message above seems harmless (although I still need to figure out what is causing it)

**Comment by fg0611** [comment] 2024-04-08 20:45
I'm using the example with controller. To reproduce:
- Home() with a Nav.push(cxt, scannerWidget)
- go back with a button Nav.pop()
- then click again to see scanner (it appears freezed).

``` 
import 'package:flutter/material.dart';
import 'package:flux/mobile_scanner_widget.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: MyHome());
  }
}

class MyHome extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: ElevatedButton(
        child: Text("QrScannerOverlay"),
        onPressed: () {
          Navigator.push(
            context,
            MaterialPageRoute(
                builder: (context) => BarcodeScannerWithController()),
          );
        },
      ),
    );
  }
}
// ----------------------- code for the mobile_scanner_widget.dart file

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

class BarcodeScannerWithController extends StatefulWidget {
  const BarcodeScannerWithController({super.key});

  @override
  State<BarcodeScannerWithController> createState() =>
      _BarcodeScannerWithControllerState();
}

class _BarcodeScannerWithControllerState
    extends State<BarcodeScannerWithController> with WidgetsBindingObserver {
  final MobileScannerController controller =
      MobileScannerController(torchEnabled: true
          // formats: [BarcodeFormat.qrCode]
          // facing: CameraFacing.front,
          // detectionSpeed: DetectionSpeed.normal
          // detectionTimeoutMs: 1000,
          // returnImage: false,
          );

  Barcode? _barcode;
  StreamSubscription<Object?>? _subscription;

  void _handleBarcode(BarcodeCapture barcodes) {
    if (mounted) {
      setState(() {
        _barcode = barcodes.barcodes[0];
      });
    }
  }

  @override
  void initState() {
    super.initState();
    // WidgetsBinding.instance.addPostFrameCallback(
    //   (_) => controller
    //     ..stop()
    //     ..start(),
    // );
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);

    switch (state) {
      case AppLifecycleState.detached:
      case AppLifecycleState.hidden:
      case AppLifecycleState.paused:
      case AppLifecycleState.resumed:
        _subscription = controller.barcodes.listen(_handleBarcode);

        unawaited(controller.start());
        return;
      case AppLifecycleState.inactive:
        unawaited(_subscription?.cancel());
        _subscription = null;
        unawaited(controller.stop());
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Container(
          width: 400,
          child: Column(
            children: [
              SizedBox(height: 30),
              Container(
                height: 200,
                width: 200,
                child: MobileScanner(
                  onDetect: _handleBarcode,
                  controller: controller,
                  fit: BoxFit.contain,
                ),
              ),
              SizedBox(height: 30),
              Text('Barcode:  ${_barcode?.rawValue}'),
              SizedBox(height: 30),
              ElevatedButton(
                  onPressed: () {
                    controller.start();
                  },
                  child: Text("start")),
              SizedBox(height: 30),
              ElevatedButton(
                  onPressed: () {
                    controller.stop();
                  },
                  child: Text("stop")),
              SizedBox(height: 30),
              ElevatedButton(
                  onPressed: () {
                    // controller.stop();
                    Navigator.of(context).pop();
                  },
                  child: Text("Back"))
            ],
          ),
        ),
      ),
    );
  }

  @override
  Future<void> dispose() async {
    WidgetsBinding.instance.removeObserver(this);
    unawaited(_subscription?.cancel());
    _subscription = null;
    super.dispose();
    controller.dispose();
  }
}

```

**Comment by joymyr** [comment] 2024-04-08 20:51
Sorry, I just assumed the message was related to why it isn't working The issue is that the MobileScanner widget is just displaying a black screen, with an exclamation mark inside. I'm not seeing any other error messages.
<img width="370" alt="Skjermbilde 2024-04-08 kl  22 46 14" src="https://github.com/juliansteenbakker/mobile_scanner/assets/255264/f3bcd72c-6671-4d82-8290-6d68467b1ded">

**Comment by fg0611** [comment] 2024-04-08 22:48
> Sorry, I just assumed the message was related to why it isn't working The issue is that the MobileScanner widget is just displaying a black screen, with an exclamation mark inside. I'm not seeing any other error messages. <img alt="Skjermbilde 2024-04-08 kl 22 46 14" width="370" src="https://private-user-images.githubusercontent.com/255264/320644135-f3bcd72c-6671-4d82-8290-6d68467b1ded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2MDk4MTksIm5iZiI6MTcxMjYwOTUxOSwicGF0aCI6Ii8yNTUyNjQvMzIwNjQ0MTM1LWYzYmNkNzJjLTY2NzEtNGQ4Mi04MjkwLTZkNjg0NjdiMWRlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOFQyMDUxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNmUzYzc0ODdiMjU4NzlkYzc2ZjkwZjIxODEzNDg0ODA1ZDUwMGFmMzEwNTE2NWVkOTMyYTIxMjk3YmQ4M2Y0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mg7H13cNKjdP8i5yB0-pDV0St7aGtMTZK1jTGCLiW70">

may I ask if you inserted 
` <script
      src="https://unpkg.com/@zxing/library@0.19.1"
      type="application/javascript"
    ></script> `
    inside index.html file?

**Comment by navaronbracke** [comment] 2024-04-09 06:10
> Sorry, I just assumed the message was related to why it isn't working The issue is that the MobileScanner widget is just displaying a black screen, with an exclamation mark inside. I'm not seeing any other error messages. <img alt="Skjermbilde 2024-04-08 kl 22 46 14" width="370" src="https://private-user-images.githubusercontent.com/255264/320644135-f3bcd72c-6671-4d82-8290-6d68467b1ded.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NDMxMjYsIm5iZiI6MTcxMjY0MjgyNiwicGF0aCI6Ii8yNTUyNjQvMzIwNjQ0MTM1LWYzYmNkNzJjLTY2NzEtNGQ4Mi04MjkwLTZkNjg0NjdiMWRlZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwNjA3MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmFjYTc1MWM5NjAyNzYwZWY0N2I1ZDE4Y2ExNWZlMGQ4YThmYjhiNjQ2ZDlhYzc5Yzc4NWNlOTdiNDQ2MzZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vktlM_DiSJKsPmLDmO7txpE68RBRLhRu9erFnzP6FSQ">

Do you have errors in the browser console?

The white exclamation mark on the black background is the default error builder for the `MobileScanner()` widget. Can you pass a custom widget, and then get the stack trace from the error details of the `MobileScannerException`, or `Exception` if for some reason we didn't catch it properly.

**Comment by joymyr** [comment] 2024-04-09 07:41
I tried to deploy to a server now, and it works, so the issue seems to be only when running on localhost/debug mode.
Still having the freezing issue on reopening though. 
When debugging locally I get no errors in the console, but from the errorBuilder I get `TypeError: null: type 'Null' is not a subtype of type 'String'`.

**Comment by navaronbracke** [comment] 2024-04-09 07:58
> I tried to deploy to a server now, and it works, so the issue seems to be only when running on localhost/debug mode. Still having the freezing issue on reopening though. When debugging locally I get no errors in the console, but from the errorBuilder I get `TypeError: null: type 'Null' is not a subtype of type 'String'`.

Yeah, the `TypeError: null: type 'Null' is not a subtype of type 'String'` is the issue I fixed locally. I still want to prepare some other changes for beta 3 (the iOS privacy manifest being one of those)

I currently have the local fix on

```
  kittens:
    git:
      url: https://github.com/navaronbracke/mobile_scanner.git
      ref: 5_0_0-beta-3
```

if you want to tinker with it.

**Comment by navaronbracke** [comment] 2024-04-09 08:11
> I'm using the example with controller. To reproduce:
> 
> * Home() with a Nav.push(cxt, scannerWidget)
> * go back with a button Nav.pop()
> * then click again to see scanner (it appears freezed).

I can reproduce this bug with the example app. I don't see any errors in the console, except for a Canvas2D warning.

**Comment by navaronbracke** [comment] 2024-04-09 13:13
Small update: I managed to fix the "frozen" camera preview locally. Still need to figure out why the ZXing barcode reader is not scanning the frames on the second attempt, but once that is done, this bug should be fixed.

**Comment by joymyr** [comment] 2024-04-09 21:00
Great, both the freezing and the TypeError: null is fixed with beta 3

**Closed** 2024-04-16 14:43 UTC
Labels: bug, web
