### ISSUE TITLE
App crashes in android release mode

### ISSUE THREAD

**Issue by orliu** [juliansteenbakker/mobile_scanner#221] opened 2022-07-07 03:33 UTC
worked fine on debug or profile.

$ flutter doctor
>
[✓] Flutter (Channel stable, 3.0.0, on macOS 11.5.1 20G80 darwin-x64, locale en-AS)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.68.1)
[✓] Connected device (3 available)

$ flutter run --release
> 
E/AndroidRuntime(22407): FATAL EXCEPTION: CameraX-core_camera_0
E/AndroidRuntime(22407): Process: com.ubisor.cloud.production_tool, PID: 22407
E/AndroidRuntime(22407): java.lang.ExceptionInInitializerError
E/AndroidRuntime(22407):        at androidx.camera.camera2.internal.s.<init>(Unknown Source:149)
E/AndroidRuntime(22407):        at androidx.camera.camera2.internal.M.<init>(Unknown Source:138)
E/AndroidRuntime(22407):        at androidx.camera.camera2.internal.t.a(Unknown Source:34)
E/AndroidRuntime(22407):        at m.G.b(Unknown Source:47)
E/AndroidRuntime(22407):        at androidx.camera.core.C.b(Unknown Source:108)
E/AndroidRuntime(22407):        at androidx.camera.core.A.run(Unknown Source:10)
E/AndroidRuntime(22407):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(22407):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(22407):        at java.lang.Thread.run(Thread.java:933)
E/AndroidRuntime(22407): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: m.n.values []
E/AndroidRuntime(22407):        at java.lang.Enum.enumValues(Enum.java:270)
E/AndroidRuntime(22407):        at java.lang.Enum.access$000(Enum.java:61)
E/AndroidRuntime(22407):        at java.lang.Enum$1.create(Enum.java:277)
E/AndroidRuntime(22407):        at java.lang.Enum$1.create(Enum.java:275)
E/AndroidRuntime(22407):        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(22407):        at java.lang.Enum.getSharedConstants(Enum.java:289)
E/AndroidRuntime(22407):        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
E/AndroidRuntime(22407):        at java.util.EnumSet.getUniverse(EnumSet.java:407)
E/AndroidRuntime(22407):        at java.util.EnumSet.noneOf(EnumSet.java:109)
E/AndroidRuntime(22407):        at java.util.EnumSet.of(EnumSet.java:283)
E/AndroidRuntime(22407):        at androidx.camera.camera2.internal.r0.<clinit>(Unknown Source:8)
E/AndroidRuntime(22407):        ... 9 more
E/AndroidRuntime(22407): Caused by: java.lang.NoSuchMethodException: m.n.values []
E/AndroidRuntime(22407):        at java.lang.Class.getMethod(Class.java:2072)
E/AndroidRuntime(22407):        at java.lang.Class.getDeclaredMethod(Class.java:2050)
E/AndroidRuntime(22407):        at java.lang.Enum.enumValues(Enum.java:267)
E/AndroidRuntime(22407):        ... 19 more

**Comment by 17020022033** [comment] 2022-07-16 11:10
I also faced this problem and fixed it through editing the configuration in build.gradle.

`    buildTypes {
        release {
            ……
            minifyEnabled false
            shrinkResources false
        }
    }
`

**Comment by nashihu** [comment] 2022-08-10 10:40
I'm switching from `qr_code_scanner` to this package because of same issue.

 i still hope it is fixed without additional setting of minify and shrinkResources

**Comment by juliansteenbakker** [comment] 2022-08-15 08:08
Can you please check if you have the following lines in your app's gradle file:

```gradle
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by 17020022033** [comment] 2022-08-15 08:29
> Can you please check if you have the following lines in your app's gradle file:
> 
> ```groovy-gradle
>  compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_8
>         targetCompatibility JavaVersion.VERSION_1_8
>     }
> ```

Yes，I do have the same compileOptions and my compileSdkVersion is 31.

**Comment by nashihu** [comment] 2022-08-15 10:07
same with me

    android {
        compileSdkVersion 33

        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_8
            targetCompatibility JavaVersion.VERSION_1_8 
        }
     
        .....

    }

**Comment by adamstyrc** [comment] 2022-08-19 12:08
Same here. I tried v `2.0.0`, `2.0.0-play-services` and `1.1.0`. For some reason just the **release** build type fails.

```
    compileSdkVersion 32

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by juliansteenbakker** [comment] 2022-08-19 13:18
Can you please share on which device you are having this issue? I can't seem to reproduce this error.

**Comment by adamstyrc** [comment] 2022-08-19 14:57
Google Pixel 5 and Pixel 6. I will try to reproduce that on example app and
possibly make a PR - maybe it's just obfuscation error

**Comment by adamstyrc** [comment] 2022-08-22 10:30
UPDATE: I was going back in versioning and seems `v1.1.0` is working properly. Is starts crashing from `v1.1.1`. Blaming change, what what [CHANGELOG](https://pub.dev/packages/mobile_scanner/changelog) says, I would bet on:
`Update camera dependency for Android.`

**Comment by adamstyrc** [comment] 2022-08-22 10:35
https://github.com/juliansteenbakker/mobile_scanner/compare/v1.1.0...v1.1.1

What do you think of reverting to camera2 v1.1.0 (which is stable now - https://developer.android.com/jetpack/androidx/releases/camera ):

**Comment by alg520** [comment] 2022-08-24 08:42
> [v1.1.0...v1.1.1](https://github.com/juliansteenbakker/mobile_scanner/compare/v1.1.0...v1.1.1)
> 
> What do you think of reverting to camera2 v1.1.0 (which is stable now - https://developer.android.com/jetpack/androidx/releases/camera ):

sound good

**Comment by juliansteenbakker** [comment] 2022-08-24 09:43
This issue is probably fixed with #257. I will release this as version 3.0.0 after i'm done with a few other functions.

**Closed by juliansteenbakker** 2022-08-24 09:43 UTC

**Comment by adamstyrc** [comment] 2022-08-31 07:11
@juliansteenbakker Great, thank you 🙌  Any clue when 3.0.0 is going to be released? I will use it immediately :)

**Comment by dishankjindal1** [comment] 2023-09-21 15:57
App is crashing for me as well on release mode.
