### ISSUE TITLE
Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by Adeel-Sultan** [juliansteenbakker/mobile_scanner#65] opened 2022-03-15 16:28 UTC
I open camera in dialog box and first time this plugin scan QR but second time it's giving this error and even if i open camera and just close dialog box also that time it  gives me this error.
It's mean only first time plugin working fine but second time not working properly

Bad state: Stream has already been listened to.
MissingPluginException(No implementation found for method listen on channel dev.steenbakker.mobile_scanner/scanner/event)

**Comment by juliansteenbakker** [comment] 2022-03-15 19:59
On which device are you having this problem, android, ios, macos or web?

**Comment by Adeel-Sultan** [comment] 2022-03-15 21:06
> On which device are you having this problem, android, ios, macos or web?

Web

**Comment by juliansteenbakker** [comment] 2022-03-15 21:23
Duplicate of #64, but thanks for reporting

**Closed by juliansteenbakker** 2022-03-15 21:23 UTC

**Comment by Adeel-Sultan** [comment] 2022-03-16 07:49
> Duplicate of #64, but thanks for reporting

Do you have any solution?

**Comment by juliansteenbakker** [comment] 2022-03-16 08:31
No not yet
