### ISSUE TITLE
ios: version conflict

### ISSUE THREAD

**Issue by RonnieLincoln** [juliansteenbakker/mobile_scanner#1166] opened 2024-08-31 01:42 UTC
Hi, mobile_scanner version: 5.2.1.

Is that possible to downgrade versions of firebase_core and firebase_auth to solve it?

```
[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/Environment":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 5.2.0, which depends on
      Firebase/Auth (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseAuth (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleUtilities/Environment (~> 8.0)

    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 3.4.0, which depends on
      Firebase/CoreOnly (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseCore (= 11.0.0) was resolved to 11.0.0, which depends on
          GoogleUtilities/Logger (~> 8.0) was resolved to 8.0.2, which depends on
            GoogleUtilities/Environment (= 8.0.2)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        MLKitBarcodeScanning (~> 5.0.0) was resolved to 5.0.0, which depends on
          MLKitCommon (~> 11.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1) was resolved to 9.4.1, which depends on
              GoogleUtilities/Environment (~> 7.7)
```

**Comment by wrteam-aayush** [comment] 2024-08-31 07:20
Having similar issues:

[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.0.1, which depends on
      Firebase/Messaging (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseMessaging (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleDataTransport (~> 10.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1)

**Comment by RonnieLincoln** [comment] 2024-08-31 08:58
I solved this problem after **downgrading a major version** of `firebase_auth` and `firebase_core`.

**Comment by UsamaKarim** [comment] 2024-08-31 09:15
Duplicate of #1165.

The solution that works. https://github.com/juliansteenbakker/mobile_scanner/issues/1165#issuecomment-2314423274

> For now this works for me... Override Firebase SDK Version in podfile
> 
> $FirebaseSDKVersion = '10.29.0'

**Comment by navaronbracke** [comment] 2024-09-01 07:15
This is a duplicate of #1165 as pointed out above.

**Closed by navaronbracke** 2024-09-01 07:15 UTC

**Comment by marjandn** [comment] 2024-09-15 07:20
firebase_core: ^2.32.0
firebase_analytics: ^10.10.7

I solved this issue but downgrade my dependencies
