### ISSUE TITLE
The widgetSize changes affecting ...RelativeToTextureInPercentage?

### ISSUE THREAD

**Issue by indeedshaw** [juliansteenbakker/mobile_scanner#745] opened 2023-09-08 09:01 UTC
Before version 3.4.0, widgetSize could be retrieved exactly. With the latest update, widgetSize becomes the screen size?
In my use case, the scanning page is not the screen size, which seems caused the scanning window to not contain QR codes well, so I thought, At this time the results calculated by calculateScanWindowRelativeToTextureInPercentage or do we expect?
[https://github.com/juliansteenbakker/mobile_scanner/blob/70f71a7956d7bca8d03e77c5ad3338b38e39cb7f/lib/src/mobile_scanner.dart#L251C51-L251C51](url)
`final Size size = MediaQuery.of(context).size`

example case:
mobile_scanner: ^3.4.1
`SizedBox(
                height: 500,
                child: MobileScanner(
                  onDetect: (BarcodeCapture capture) =>
                      _handleOnDetect(capture),
                  controller: _controller,
                  scanWindow: Rect.fromCenter(
                      center: Offset((screenWidth - 300) / 2,
                          (screenHeight - 300) / 2),
                      width: 300,
                      height: 300),
                ),
              ),`

**Comment by indeedshaw** [comment] 2023-09-08 09:05
Although the way things are computed today is a bit different than before, the idea is really brilliant
[https://github.com/juliansteenbakker/mobile_scanner/pull/176](url)

**Comment by indeedshaw** [comment] 2023-09-08 09:13
That's a brilliant idea
[https://github.com/juliansteenbakker/mobile_scanner/pull/176#issue-1259922838](url)

**Comment by jlin5** [comment] 2023-09-15 16:03
I'm experiencing the same issue as well with the same use case. It looks like **LayoutBuilder** was removed to solve an issue where **IntrinsicHeight** could not be used for the placeholder / error builder. https://github.com/juliansteenbakker/mobile_scanner/pull/559

Can the **LayoutBuilder** be added back to get the correct widget size? Otherwise the **calculateScanWindowRelativeToTextureInPercentage** method will have to change it's calculation based on the screen size instead of the widget size.

@juliansteenbakker @navaronbracke

**Comment by navaronbracke** [comment] 2023-09-15 16:39
@navaronbracke I can revert my original change so that a LayoutBuilder is used.

I'll have to test if I can reproduce the issue with the IntrinsicHeight, maybe just wrapping said widget in an Align fixes that issue as well?

**Comment by jlin5** [comment] 2023-09-18 13:52
I'm not sure how to reproduce the IntrinsicHeight issue. I returned a widget with IntrinsicHeight in the errorBuilder property and I don't get an error. 🤔

**Comment by navaronbracke** [comment] 2023-09-18 14:00
Feel free to revert my change in a PR then :) I still have some other work to do, so I might not get to this myself.

**Comment by indeedshaw** [comment] 2023-09-19 03:41
I agree that it may not be possible to get an accurate widgetSize in special cases, and we need to go deeper. Maybe we can add the exact size field.

**Comment by jlin5** [comment] 2023-09-19 03:52
I just found out that this pull request https://github.com/juliansteenbakker/mobile_scanner/pull/721 added back the LayoutBuilder widget. I can close the PR I created in favor of https://github.com/juliansteenbakker/mobile_scanner/pull/721 if that gets merged in first.

**Comment by navaronbracke** [comment] 2023-10-12 19:21
The scan window fix in #721 has been merged. So I'm going to close this issue as completed.

**Closed by navaronbracke** 2023-10-12 19:21 UTC
