### ISSUE TITLE
[Bug] Mobile scanner not dispose on Web 

### ISSUE THREAD

**Issue by Trung15010802** [juliansteenbakker/mobile_scanner#1118] opened 2024-07-05 09:49 UTC

**Comment by navaronbracke** [comment] 2024-07-07 11:08
This is probably a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1087 ?

**Comment by Trung15010802** [comment] 2024-07-07 11:22
> This is probably a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1087 ?

That's right

**Closed** 2024-07-07 11:25 UTC
