### ISSUE TITLE
[Crash] In android, MissingPluginException(No implementation found for method torch on channel dev.steenbakker.mobile_scanner/scanner/method)

### ISSUE THREAD

**Issue by binhvtKova** [juliansteenbakker/mobile_scanner#684] opened 2023-07-07 02:42 UTC
I'm using version *mobile_scanner: ^3.3.0* in my project. 
When I run on Android real device, get crash when using torch method like below.

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: MissingPluginException(No implementation found for method torch on channel dev.steenbakker.mobile_scanner/scanner/method)
       at MethodChannel._invokeMethod(platform_channel.dart:313)
       at MobileScannerController.toggleTorch(mobile_scanner_controller.dart:280)
```

I've searched some helps and find this, maybe can help. 
https://stackoverflow.com/questions/70562128/unhandled-exception-missingpluginexceptionno-implementation-found-for-method-s

Please help me to make a fix for this. 
Thanks

**Comment by navaronbracke** [comment] 2023-10-29 14:48
@binhvtKova Does this reproduce on version 3.5.1 ? We no longer use a FlutterFragmentActivity.

**Comment by jokerknight** [comment] 2024-01-23 06:44
`MissingPluginException(No implementation found for method listen on channel dev.steenbakker.mobile_scanner/scanner/event)
`
same error, almost blocked to use. if you can't resolve this issue just publish a worked version to flutter plugin market?

**Comment by navaronbracke** [comment] 2024-01-23 08:24
Does this reproduce on the example app with version 3.5.6 ?

**Comment by Kancheraj** [comment] 2024-03-25 05:58
flutter: MissingPluginException(No implementation found for method listen on channel dev.steenbakker.mobile_scanner/scanner/event)
flutter: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332)
flutter: <asynchronous suspension>
flutter: #1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:676)
flutter: <asynchronous suspension>

yes its occurring in version mobile_scanner: ^4.0.1 , please help me

**Comment by navaronbracke** [comment] 2024-03-25 07:09
Could you provide a minimal reproducible sample? 
This sounds like you're forgetting to call `WidgetsFlutterBinding.ensureInitialized();` before using the plugin.

Some additional questions:
1) Are you running in release mode?
2) Could you provide your pubspec.lock file?
3) Did you run `flutter clean && flutter pub get`

**Comment by Kancheraj** [comment] 2024-03-25 07:20
Yes I’m running in release mode to test in real iPhone device, may be this is issue related to camera permission.im using permission_handler packager for handling the permission.

In initstate I’m calling these method to get camera permission.
WidgetsFlutterBinding.ensureInitialized();
    bloc.add(CheckPermissionEvent(context));
on builder widget
MobileScanner(
                      errorBuilder: (context, error, child) {
                        return ScannerErrorWidget(error: error);
                      },
                      onDetect: (capture) {
                        final List<Barcode> barcodes = capture.barcodes;
                        for (final barcode in barcodes) {
                          print('Barcode found! ${barcode.rawValue}');
                        }
                      },
                    ),


Note : if I don’t use the permission_handler it will work fine.



Internal

From: Navaron Bracke ***@***.***>
Date: Monday, 25 March 2024 at 12:39 PM
To: juliansteenbakker/mobile_scanner ***@***.***>
Cc: Kanche Rajkumar ***@***.***>, Comment ***@***.***>
Subject: [Ext] Re: [juliansteenbakker/mobile_scanner] [Crash] In android, MissingPluginException(No implementation found for method torch on channel dev.steenbakker.mobile_scanner/scanner/method) (Issue #684)
CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.


Could you provide a minimal reproducible sample?
This sounds like you're forgetting to call WidgetsFlutterBinding.ensureInitialized(); before using the plugin.

Some additional questions:

  1.  Are you running in release mode?
  2.  Could you provide your pubspec.lock file?
  3.  Did you run flutter clean && flutter pub get

**Comment by andrewcortez1** [comment] 2024-07-19 06:22
same problem

**Comment by RyamBaCo** [comment] 2024-11-27 12:24
Hey there,

stumbled across this thread by having the same issue.

Solved it in my case by updating the firebase_messaging-Dependencies in my project. Thanks for indirectly giving me the hint for checking up other permission libraries, so I identified firebase_messaging (also asking for permissions) as possible culprit.

**Comment by navaronbracke** [comment] 2024-11-27 13:48
Since this seems to be a dependency issue, I'm going to close this issue.

**Closed by navaronbracke** 2024-11-27 13:48 UTC
