### ISSUE TITLE
Ios Simulator List View Jank

### ISSUE THREAD

**Issue by BraydenKlemens** [juliansteenbakker/mobile_scanner#1149] opened 2024-08-13 23:45 UTC
When adding this package to any flutter project it causes jank frames on the ios simulator. This occurs when performing any animation such as switching between tab-bar tabs or scrolling a list view. Current device is apple m1.

**Comment by navaronbracke** [comment] 2024-08-14 06:25
Could you provide a minimal reproducible sample? Scrolling jank can have multiple reasons. I doubt that the inclusion of a PlatformView for the camera preview would cause scrolling jank in this case.

What version of the library are you using?

**Comment by BraydenKlemens** [comment] 2024-08-14 17:50
**Here is a Video of the list view jank with a brand new flutter project**
https://github.com/user-attachments/assets/6b2329ae-38c6-4e1f-843c-ff5ecd01bb7f

**Versions:**
- Flutter 3.24.0 
- Tools • Dart 3.5.0 • DevTools 2.37.2
- mobile_scanner: 5.1.1
- IOS iphone 15 pro max 17.5

**Steps to Reproduce**
- Create new flutter project
- add listview.builder with List Tiles
- pub add mobile_scanner
- pub get
- debug - > jank

`void main() {
  runApp(const MyApp());
}
class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}
class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key, required this.title});
  final String title;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(title),
      ),
      body: ListView.builder(
        itemCount: 15,
        itemBuilder: (context, index) {
          return Padding(
            padding: const EdgeInsets.all(8.0),
            child: ListTile(
              tileColor: Colors.deepPurple.shade100,
              title: Text('Item $index'),
            ),
          );
        },
      ),
    );
  }
}`

**Comment by haven-git** [comment] 2024-08-17 07:10
same issue

**Comment by fmaerkl-sw** [comment] 2024-08-23 07:13
This is due to #1018 when the app is run through Rosetta automatically.

**Comment by navaronbracke** [comment] 2024-08-23 10:29
> This is due to #1018 when the app is run through Rosetta automatically.

Interesting finding! I'm not sure if MLKit supports arm64 Simulators, so we would have to look into that.

But then the list view jank is just because the app is ran through Rosetta?

> What Flutter version are you using?

@BraydenKlemens I'll have to ask again, what Flutter version are you on? Earlier Flutter versions used Rosetta when running on arm64 (and I believe that was also the case for the iOS Simulator)

Could you try to see if this also happens with the latest Flutter version? (or maybe one of the last three stable releases)

**Comment by fmaerkl-sw** [comment] 2024-08-23 10:31
> But then the list view jank is just because the app is ran through Rosetta?

Yes. Likely the JIT used by Flutter in Debug mode does not play well with the translation.

**Comment by BraydenKlemens** [comment] 2024-08-24 14:06
@navaronbracke flutter version is 3.24. Please refer to previous post for a list of versions.

**Comment by navaronbracke** [comment] 2024-08-24 14:18
Ah, yes sorry I missed that. Could still be something with arm64 iOS Simulators though

**Comment by navaronbracke** [comment] 2024-08-24 15:22
Does this reproduce with Impeller off?

**Comment by theSharpestTool** [comment] 2024-08-29 10:08
Hi @navaronbracke @BraydenKlemens I've also faced with it. Looks like the issue doesn't occur with Impeller off:

Impeller without the package
<img width="669" alt="Screenshot 2024-08-29 at 12 47 02" src="https://github.com/user-attachments/assets/3242d54b-2ea2-4163-90af-40ff52a65f1f">

Impeller with the package
<img width="669" alt="Screenshot 2024-08-29 at 12 44 06" src="https://github.com/user-attachments/assets/9f3ac5ea-d5a9-46ac-819b-eb411c64a5db">

Skia with/without package
<img width="669" alt="Screenshot 2024-08-29 at 12 56 16" src="https://github.com/user-attachments/assets/d55cca0a-df47-4e1a-a95e-30945c91fa2b">

**Comment by vital-edu** [comment] 2024-10-31 12:05
This is fixed in the version `7.0.0-beta.3` https://github.com/juliansteenbakker/mobile_scanner/issues/1225

**Comment by navaronbracke** [comment] 2024-10-31 17:56
Per the above comment, I'm going to close this issue.

**Closed by navaronbracke** 2024-10-31 17:56 UTC
