### ISSUE TITLE
 CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core"

### ISSUE THREAD

**Issue by FynnFrings** [juliansteenbakker/mobile_scanner#442] opened 2023-01-04 21:58 UTC
When trying to run my App i get that error (caused by firebase_storage using a different version of GTMSessionFetcher/Core). What can I do about it?

(The 2 suggestions at the bottom don't work)

```
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In snapshot (Podfile.lock):
    GTMSessionFetcher/Core (< 4.0, = 3.0.0, >= 2.1)

  In Podfile:
    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 3.2.0) was resolved to 3.2.0, which depends on
        MLKitBarcodeScanning (~> 2.2.0) was resolved to 2.2.0, which depends on
          MLKitVision (~> 4.2) was resolved to 4.2.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `GTMSessionFetcher/Core` inside your development pod `mobile_scanner`.
   You should run `pod update GTMSessionFetcher/Core` to apply changes you've made.
```

**Comment by vkbaloda** [comment] 2023-01-08 09:19
Hello Fynn, can you please confirm if this solution is working?

I got an error on ^3.0.0-beta.4

```
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding-UTF8
/C:/src2/flutter/.pub-cache/hosted/pub.dartlang.org/mobile_scanner-3.0.0-beta.4/lib/src/mobile_scanner_controller.dart:355:38: Error: 'Uint8List' isn't a type.
            image: event['image'] as Uint8List?,
                                     ^^^^^^^^^
```
`dart:typed_data` import is missing in the controller file

**Comment by dangduoc** [comment] 2023-02-02 17:18
I've got the same problem. is this gonna be fixed soon?

**Comment by juliansteenbakker** [comment] 2023-02-09 21:08
This problem is fixed in version 3.0.0.

**Comment by CoryADavis** [comment] 2023-02-13 18:42
> I've got the same problem. is this gonna be fixed soon?

This is exclusively a GoogleMLKit issue, and the solution linked in this thread should work for most if not all use cases. Unfortunately, there is currently no indication of when Google will update the library and remove the need for this workaround.

**Comment by juliansteenbakker** [comment] 2023-02-15 16:59
Im closing this as duplicate of #335, there's not much i can do right now about this.

**Closed by juliansteenbakker** 2023-02-15 16:59 UTC

**Comment by davindermakkar** [comment] 2023-03-05 17:13
I m using the mobile scanner pick image from gallery. I m able to get to the point where qr code is detected but after analyse image returns true how will i get the data? Please if someone can help
