### ISSUE TITLE
Camera not starts on web on ios

### ISSUE THREAD

**Issue by Gegerout** [juliansteenbakker/mobile_scanner#969] opened 2024-03-03 18:06 UTC
Camera not starts (full white screen) when testing on Safari on iOS for web
![photo_2024-03-03_21-05-48](https://github.com/juliansteenbakker/mobile_scanner/assets/72309553/07a68fea-c1bd-4f5a-a3ce-365f55a1c71b)

**Comment by navaronbracke** [comment] 2024-03-05 09:48
Could you provide the logs from the browser console?

You can access these by 
- connecting your iOS device to a Mac
- open Safari
- select the `Develop` option in the MacOS toolbar
- open the JS console for the attached device

**Comment by navaronbracke** [comment] 2024-03-05 09:52
Apparently this is a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/950

Going to close this issue, so that we can follow up there.

**Closed by navaronbracke** 2024-03-05 09:52 UTC
