### ISSUE TITLE
When used on a horizontal screen, the camera direction is wrong

### ISSUE THREAD

**Issue by KamiWen** [juliansteenbakker/mobile_scanner#239] opened 2022-07-27 06:02 UTC
When used on a horizontal screen, the camera direction is wrong

![image](https://user-images.githubusercontent.com/24468776/181172638-4784eb59-880e-4a7f-9425-0fef2d4b0c84.png)

**Comment by KamiWen** [comment] 2022-07-27 06:04
My code
`import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

class TestQr extends StatelessWidget {
  const TestQr({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MobileScanner(
        allowDuplicates: false,
        onDetect: (barcode, args) {
          if (barcode.rawValue == null) {
            debugPrint('Failed to scan Barcode');
          } else {
            final String code = barcode.rawValue!;
            debugPrint('Barcode found! $code');
          }
        });
  }
}
`

**Comment by patrick-vieira** [comment] 2022-08-09 03:10
I faced the same issue, for now i just wrapped the MobileScanner with an RotatedBox with 3 quarterTurns when in landscape

**Comment by KamiWen** [comment] 2022-08-11 06:49
> I faced the same issue, for now i just wrapped the MobileScanner with an RotatedBox with 3 quarterTurns when in landscape

It's work, thanks.

**Comment by nemanja-nisic** [comment] 2022-08-12 14:52
@patrick-vieira That works, but it letterboxes the scanner. Is there a way to resolve that as well?

**Comment by MrNB0dy** [comment] 2022-09-02 13:03
hi, has this been fixed? when will the new version be released on pubdev?

**Comment by clemsciences** [comment] 2022-09-26 15:39
> I faced the same issue, for now i just wrapped the MobileScanner with an RotatedBox with 3 quarterTurns when in landscape

It works with the package [native_device_orientation](https://pub.dev/packages/native_device_orientation) and `NativeDeviceOrientationReader` widget but it the controller for the torch and to switch camera does not work anymore.

**Comment by seanhamstra** [comment] 2022-11-04 16:26
+1 landscape is actually portrait and the wrong way.

**Comment by aarajput** [comment] 2022-11-26 14:54
I am facing same issue

**Comment by seanhamstra** [comment] 2022-12-05 18:27
I haven't had time for a PR and this fix relies on `native_device_orientation` put perhaps it will help others:

```
// ignore_for_file: comment_references

import 'dart:async';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import 'package:native_device_orientation/native_device_orientation.dart';

/// A widget showing a live camera preview.
/// SH: this is our modified version to fix landscape.
class MobileScannerMod extends StatefulWidget {
  /// Create a [MobileScanner] with a [controller], the [controller] must has
  /// been initialized.
  const MobileScannerMod({
    super.key,
    this.onDetect,
    this.controller,
    this.allowDuplicates = false,
  });

  /// The controller of the camera.
  final MobileScannerController? controller;

  /// Function that gets called when a Barcode is detected.
  ///
  /// [barcode] The barcode object with all information about the scanned code.
  /// [args] Information about the state of the MobileScanner widget
  final void Function(Barcode barcode, MobileScannerArguments args)? onDetect;

  /// Set to false if you don't want duplicate scans.
  final bool allowDuplicates;

  @override
  State<MobileScannerMod> createState() => _MobileScannerModState();
}

class _MobileScannerModState extends State<MobileScannerMod>
    with WidgetsBindingObserver {
  late MobileScannerController controller;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    controller = widget.controller ?? MobileScannerController();
    if (Platform.isIOS) restart(); // bug on first launch, doesnt always init
  }

  /// Restarts the camera controller after frame delay
  Future<void> restart() async {
    await Future<void>.delayed(Duration.zero);
    await controller.stop();
    while (controller.isStarting) {
      // Prevent start while still starting up (throws)
      await Future<void>.delayed(Duration.zero);
    }
    await controller.start();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    switch (state) {
      case AppLifecycleState.resumed:
        if (!controller.isStarting) controller.start();
        break;
      case AppLifecycleState.inactive:
      case AppLifecycleState.paused:
      case AppLifecycleState.detached:
        controller.stop();
        break;
    }
  }

  String? lastScanned;

  @override
  Widget build(BuildContext context) {
    final mustRotate =
        MediaQuery.of(context).orientation == Orientation.landscape;

    return LayoutBuilder(
      builder: (context, BoxConstraints constraints) {
        return ValueListenableBuilder(
          valueListenable: controller.args,
          builder: (context, value, child) {
            if (value == null) {
              return const ColoredBox(color: Colors.black);
            } else {
              controller.barcodes.listen((barcode) {
                if (!widget.allowDuplicates) {
                  if (lastScanned != barcode.rawValue) {
                    lastScanned = barcode.rawValue;
                    widget.onDetect!(barcode, value);
                  }
                } else {
                  widget.onDetect!(barcode, value);
                }
              });

              // this some black magic here.
              // Basically the texture is always sized as portrait.
              // We can simply rotate, but scaling it to fit is ideal
              // so we do that!
              final cameraBox = FittedBox(
                fit: BoxFit.none,
                child: SizedBox(
                  width: mustRotate
                      ? (constraints.maxWidth * value.size.aspectRatio)
                      : (constraints.maxHeight * value.size.aspectRatio),
                  height: mustRotate
                      ? (constraints.maxWidth)
                      : constraints.maxHeight,
                  // ignore: dead_null_aware_expression
                  child: Texture(textureId: value.textureId ?? 0),
                ),
              );
              return SizedBox(
                width: constraints.maxWidth,
                height: constraints.maxHeight,
                child: NativeDeviceOrientedWidget(
                  landscapeRight: (context) => RotatedBox(
                    quarterTurns: 1,
                    child: cameraBox,
                  ),
                  landscapeLeft: (context) => RotatedBox(
                    quarterTurns: 3,
                    child: cameraBox,
                  ),
                  portraitUp: (context) => cameraBox,
                  portraitDown: (context) => RotatedBox(
                    quarterTurns: 2,
                    child: cameraBox,
                  ),
                  fallback: (context) => RotatedBox(
                    quarterTurns: mustRotate ? 3 : 0,
                    child: cameraBox,
                  ),
                ),
              );
            }
          },
        );
      },
    );
  }

  @override
  void didUpdateWidget(covariant MobileScannerMod oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.controller == null) {
      if (widget.controller != null) {
        controller.dispose();
        controller = widget.controller!;
      }
    } else {
      if (widget.controller == null) {
        controller = MobileScannerController();
      } else if (oldWidget.controller != widget.controller) {
        controller = widget.controller!;
      }
    }
  }

  @override
  void dispose() {
    controller.dispose();
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }
}

```

**Comment by juliansteenbakker** [comment] 2022-12-14 19:33
Duplicate of #12

**Closed by juliansteenbakker** 2022-12-14 19:33 UTC
Labels: bug, landscape mode

**Comment by collinsyu** [comment] 2024-06-21 03:52
> I faced the same issue, for now i just wrapped the MobileScanner with an RotatedBox with 3 quarterTurns when in landscape

真有你的
