### ISSUE TITLE
TF Lite in Google Play services has stable ABI version 1.11.0 which is less than the required version 1.13.0

### ISSUE THREAD

**Issue by rachitjoshi9** [juliansteenbakker/mobile_scanner#836] opened 2023-10-28 02:05 UTC
We are using   mobile_scanner: ^3.5.1 version in our flutter project, on android device when ever camera opens below warning keeps on coming repeatedly

W/native  (30072): W0000 00:00:1698456375.622782   32103 abi_method_util.h:33] not supported: TfLiteInterpreterGetTensor: TF Lite in Google Play services has stable ABI version 1.11.0 which is less than the required version 1.13.0.

environment:
  sdk: '>=2.12.0 <3.0.0'

Where do we need to make changes to upgrade to required version 1.13.0

**Comment by navaronbracke** [comment] 2023-10-29 10:38
As far as I know, `Tensor Flow Lite` is a dependency of MLKit. I think we have to bump the version of MLKit that is used to get rid of this warning. I'll look into this.

**Comment by rachitjoshi9** [comment] 2023-10-30 04:42
Thanks for update, we will be waiting for this change to be done in new version.

**Comment by dhirajmishra98** [comment] 2023-11-06 02:25
the issue is still pending!

**Comment by navaronbracke** [comment] 2023-11-06 07:09
@dhirajmishra98 As I mentioned in https://github.com/juliansteenbakker/mobile_scanner/issues/836#issuecomment-1787248290 the MLKit version has been updated to the latest available version in `mobile_scanner 3.5.2`.
If this issue is still occurring, we cannot do anything at the moment since version 18.3.0 is the latest version.

See https://developers.google.com/ml-kit/release-notes#latest_versions

**Comment by navaronbracke** [comment] 2023-11-06 09:33
Could @rachitjoshi9 or @dhirajmishra98 reply to https://github.com/tensorflow/tensorflow/issues/62331 with the following information:

- Device info of the Android device (`adb shell getprop ro.build.fingerprint`)
- Google Play Services version (Settings > Apps > Google Play Services > App details)

**Comment by navaronbracke** [comment] 2023-11-06 09:45
Apparently support for version 1.13.0 is still in preview. Is anyone using preview/beta versions here?

**Comment by LaPyaeOo** [comment] 2023-11-13 08:41
This issue still happen. I used `mobile_scanner: ^3.5.2`. After that first time opening the camera still get 
```
TF Lite in Google Play services has stable ABI version 1.11.0 which is less than the required version 1.13.0
```
and can't use. Only work in second time after enter again to this screen.

**Comment by asavchuk** [comment] 2023-11-23 06:52
I use `simple_barcode_scanner` and got a lot of outputs in console 
> TF Lite in Google Play services has stable ABI version 1.11.0 which is less than the required version 1.13.0.

**Comment by YedekTunahan** [comment] 2023-11-24 10:18
TF Lite on Google Play services has a stable ABI version of 1.13.0, which is less than the required version 1.11.0. Does the problem still persist

**Comment by officialismailshah** [comment] 2023-11-25 22:00
yes problem still persists...

**Comment by officialismailshah** [comment] 2023-11-25 22:27
is there a work around it?

**Comment by officialismailshah** [comment] 2023-11-25 23:13
For beginners, I have used the bundled version,
there is no exception about the TF Lite in Google Play services has stable ABI version 1.11.0 which is less than the required version 1.13.0
 just remove "dev.steenbakker.mobile_scanner.useUnbundled=true"

**Comment by iruuuuull** [comment] 2023-11-28 07:26
Is there any way to solve it?

**Comment by fergushenderson** [comment] 2024-04-12 09:25
I'm on the "TF Lite in Play services" team at Google, and I just came across this issue.
(For faster support on similar issues in future, file an issue in the tensorflow github issues list, and tag it with the appropriate tags to indicate that it is related to TF Lite in Play services.)

I believe this issue should be fixed already, by an updated version of TF Lite in Play services, with no need for code changes or even recompilation for apps that were previously affected. If the issue is still occuring, please let us know.

**Comment by navaronbracke** [comment] 2024-04-13 09:07
Thanks for the update

> I'm on the "TF Lite in Play services" team at Google, and I just came across this issue. (For faster support on similar issues in future, file an issue in the tensorflow github issues list, and tag it with the appropriate tags to indicate that it is related to TF Lite in Play services.)
> 
> I believe this issue should be fixed already, by an updated version of TF Lite in Play services, with no need for code changes or even recompilation for apps that were previously affected. If the issue is still occuring, please let us know.

Thanks for the update. I'll keep that in mind for future similar reports here.

**Closed** 2024-04-13 09:07 UTC
Labels: MLKit
