### ISSUE TITLE
Uncaught zxing exception `TypeError: Cannot set properties of null (setting 'AbstractExpandedDecoder')`

### ISSUE THREAD

**Issue by jorgenpt** [juliansteenbakker/mobile_scanner#676] opened 2023-06-25 22:51 UTC
I'm having a hard time tracking down what's happening here, but when starting up my app in VSCode under the debugger for the web target, I'm getting an uncaught exception:
`TypeError: Cannot set properties of null (setting 'AbstractExpandedDecoder')`

It doesn't give me any context about where this is raised from, and it's not triggering my `PlatformDispatcher.instance.onError` callback. Stepping through the code, it seems to be originating the first time `main` does an `await`. E.g. when I step through this code, it happens while stepping over the `await`:

```dart
Future<void> main() async {
  PlatformDispatcher.instance.onError = (error, stack) {
    FlutterError.presentError(FlutterErrorDetails(exception: error, stack: stack));
    return true;
  };

  await Future.delayed(const Duration(seconds: 1));
  WidgetsFlutterBinding.ensureInitialized();
```

![image](https://github.com/juliansteenbakker/mobile_scanner/assets/21258/8b2e5063-386d-4549-8c0c-c2d7a74e77af)

This seems to be caught by the "Uncaught Exceptions" breakpoint in VS Code -- disabling it just means I get the following in the log:

```
TypeError: Cannot set properties of null (setting 'AbstractExpandedDecoder')
https://unpkg.com/@zxing/library@0.19.1 15:288561  <fn>
https://unpkg.com/@zxing/library@0.19.1 1:69       <fn>
https://unpkg.com/@zxing/library@0.19.1 1:206      <fn>
```

If I do that, I can also catch it in the Chrome debugger, and if I apply the source map, it turns into this line: `exports.AbstractExpandedDecoder = AbstractExpandedDecoder;` -- where `exports` is `null`.

Version info:
```
Flutter 3.10.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 796c8ef792 (12 days ago) • 2023-06-13 15:51:02 -0700
Engine • revision 45f6e00911
Tools • Dart 3.0.5 • DevTools 2.23.1
```

Using mobile_scanner from master (with https://github.com/juliansteenbakker/mobile_scanner/pull/675)

**Comment by navaronbracke** [comment] 2023-06-28 06:44
@juliansteenbakker This is a duplicate of #622

**Closed** 2023-06-30 08:55 UTC
