### ISSUE TITLE
Multiple instance issue : black screen

### ISSUE THREAD

**Issue by EArminjon** [juliansteenbakker/mobile_scanner#446] opened 2023-01-11 16:49 UTC
## Issue : 

Cannot start scanner after a dispose from an other instance (or related).

## What we see

We can push one or several pages which contain a scanner
When we pop this page and go back, previous scanner won't start, despite the .start() method...

## Version 

Flutter 3.3.4
mobile_scanner: ^3.0.0-beta.4

[untitled.webm](https://user-images.githubusercontent.com/37028599/211865939-69d689d6-87d9-4052-8914-74e198876d4f.webm)

```dart
import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';

void main() => runApp(const MaterialApp(home: MyHome()));

class MyHome extends StatelessWidget {
  const MyHome({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Flutter Demo Home Page')),
      body: SizedBox(
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            ElevatedButton(
              onPressed: () {
                Navigator.of(context).push(
                  MaterialPageRoute<dynamic>(
                    builder: (BuildContext context) =>
                        const BarcodeScannerWithController(),
                  ),
                );
              },
              child: const Text('MobileScanner with Controller'),
            ),
          ],
        ),
      ),
    );
  }
}

class BarcodeScannerWithController extends StatefulWidget {
  const BarcodeScannerWithController({super.key});

  @override
  _BarcodeScannerWithControllerState createState() =>
      _BarcodeScannerWithControllerState();
}

class _BarcodeScannerWithControllerState
    extends State<BarcodeScannerWithController>
    with SingleTickerProviderStateMixin {
  BarcodeCapture? barcode;

  final MobileScannerController controller = MobileScannerController(
    torchEnabled: true,
    // formats: [BarcodeFormat.qrCode]
    // facing: CameraFacing.front,
    // detectionSpeed: DetectionSpeed.normal
    // detectionTimeoutMs: 1000,
    // returnImage: false,
  );

  bool isStarted = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(controller.hashCode.toString()),
      ),
      backgroundColor: Colors.black,
      floatingActionButton: FloatingActionButton(
        child: const Icon(Icons.camera),
        onPressed: () async {
          await controller.stop();
          await Navigator.of(context).push(
            MaterialPageRoute<dynamic>(
              builder: (BuildContext context) =>
                  const BarcodeScannerWithController(),
            ),
          );
          await controller.start();
        },
      ),
      body: Builder(
        builder: (BuildContext context) {
          return Stack(
            children: <Widget>[
              MobileScanner(
                controller: controller,
                errorBuilder: (
                  BuildContext context,
                  MobileScannerException error,
                  Widget? child,
                ) {
                  return ScannerErrorWidget(error: error);
                },
                fit: BoxFit.contain,
                onDetect: (BarcodeCapture barcode) {
                  setState(() {
                    this.barcode = barcode;
                  });
                },
              ),
            ],
          );
        },
      ),
    );
  }

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }
}

class ScannerErrorWidget extends StatelessWidget {
  const ScannerErrorWidget({super.key, required this.error});

  final MobileScannerException error;

  @override
  Widget build(BuildContext context) {
    String errorMessage;

    switch (error.errorCode) {
      case MobileScannerErrorCode.controllerUninitialized:
        errorMessage = 'Controller not ready.';
        break;
      case MobileScannerErrorCode.permissionDenied:
        errorMessage = 'Permission denied';
        break;
      default:
        errorMessage = 'Generic Error';
        break;
    }

    return ColoredBox(
      color: Colors.black,
      child: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Padding(
              padding: EdgeInsets.only(bottom: 16),
              child: Icon(Icons.error, color: Colors.white),
            ),
            Text(
              errorMessage,
              style: const TextStyle(color: Colors.white),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by cody1024d** [comment] 2023-01-13 01:25
I'm having a similar issue. Albeit mine is not back-to-back scanners, but a scanner, and then a standard camera view.

I call `controller.dispose()` before navigating to the next screen, however, I still see this being thrown (on an Android device) in the logs:

```
01-12 19:52:05.561  1090  2244 I CameraService: CameraService::connect call (PID -1 "com.verfico.app", camera ID 1) for HAL version default and Camera API version 2
01-12 19:52:05.562  1090  2244 E CameraService: CameraService::connect X (PID 1642) rejected (existing client(s) with higher priority).
```

I have confirmed that if I remove the scanning screen, and just load the user into the camera widget, that it loads properly.

**Comment by cody1024d** [comment] 2023-01-13 13:44
@EArminjon 

I am pulling straight from the master branch, but yes it would be the latest code (similar to beta pub). Have you tried any earlier versions?

**Comment by EArminjon** [comment] 2023-01-17 17:18
This issue is major for us :'(
I tried to investigate your library but i think it's more native part and i can't help more :/

**Comment by NAME-NikhilPatil** [comment] 2023-01-23 18:14
start controller.start() in initstate

**Comment by EArminjon** [comment] 2023-01-23 18:43
> start controller.start() in initstate

Have you tried my example and try with your solution ? Do it allow to open many windows with camera without issue and pop them one by one restarting each camera when screen come back to visibility ?

**Comment by cody1024d** [comment] 2023-01-26 13:49
Hey @EArminjon ,

So I ended up resolving my issue; but I'm not sure it will work in your usecase.

So the problem is that the controller.stop/dispose (that stops the controller) calls into the native Android code, which ends up unbinding the CameraX lifecycle listener. I did some research, and basically, this unbinding is **asynchronous**, and doesn't notify the caller, at all. So it's very possible, that while you're opening new screens, that the previous is still disconnecting.

I figured this out based on the errors I was specifically seeing from my device logs (client rejected, etc.).

In my case, I closed the camera sooner; as well as added retry mechanisms when trying to "start" the camera on the next screen

**Comment by EArminjon** [comment] 2023-01-26 14:38
Hum could be interesting to create a PR to await this asynchronous method call. Can you ?

**Comment by cody1024d** [comment] 2023-01-26 19:36
Unfortunately, the Android platform itself has no hook back (as far as I could tell) when unbinding, so I'm not sure that'd be possible

**Closed** 2023-02-03 13:43 UTC

**Comment by EArminjon** [comment] 2023-02-13 10:13
@juliansteenbakker issue above is still reproducible :/ 

I tried to add  `startDelay: true`inside `MobileScanner`but same issue.

**Comment by EArminjon** [comment] 2023-02-21 08:41
I created on my app a temporary fix : i made a loop around the .start to retry 3 times with a little delay. Not clean at all but it work for us.

**Comment by cody1024d** [comment] 2023-02-24 21:41
> I created on my app a temporary fix : i made a loop around the .start to retry 3 times with a little delay. Not clean at all but it work for us.

I've actually done something similar, although I can still get my app into an unusable state :( Specifically with very aggressive use of the home button, and app switching (in Android). I believe this framework is somehow holding onto a lifecycle binding somewhere too long.
