### ISSUE TITLE
UserDefault out of date

### ISSUE THREAD

**Issue by yegenpres** [juliansteenbakker/mobile_scanner#1187] opened 2024-09-21 18:09 UTC
![Image 21-09-2024 at 20 08](https://github.com/user-attachments/assets/2e115330-a392-4fd0-b0c4-1b230580a198)

Please update dependency, really need this package .

**Comment by navaronbracke** [comment] 2024-09-23 11:24
This is a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1165

**Closed by navaronbracke** 2024-09-23 11:24 UTC
