### ISSUE TITLE
[MacOS] Type is always unknown

### ISSUE THREAD

**Issue by JulienDev** [juliansteenbakker/mobile_scanner#848] opened 2023-11-03 13:58 UTC
Hello guys,
Each time I scan a code (ean13/qrcode...) the type is `unknown` on MacOS. When I'm scanning the exact same codes using the iOS and Android libraries the types are recognized properly. The raw value looks ok so I think the issue really comes from the type detection.
Any idea how I could fix the issue?
Thanks

Versions tested: 3.4.x and 3.5.x

**Comment by navaronbracke** [comment] 2023-11-03 14:00
Do you have an example of a code that does not scan correctly? I'll take a look.

**Comment by JulienDev** [comment] 2023-11-03 14:14
Sure, you can test with this code for example :)

![Screenshot_20231103-151117](https://github.com/juliansteenbakker/mobile_scanner/assets/71345/dd938430-b527-49ab-ae49-88ea72a9fed8)

This is the scan result for MacOS:
```
flutter: barcode type:BarcodeType.unknown
flutter: barcode rawValue:WIFI:T:WPA;S:Ssid;P:Password;H:;;
```

and with the same code on iOS:
```
flutter: barcode type:BarcodeType.wifi
flutter: barcode rawValue:WIFI:T:WPA;S:Ssid;P:Password;H:;;
```

**Comment by navaronbracke** [comment] 2023-11-03 14:22
I see what the problem is. So the raw value and the format are correct, but the BarcodeType (which is not the same as the format, in this case the format is a QR code) is never set, because on MacOS, we do not have that information (yet?).

I'll see if we can retrieve this information from the native MacOS result.

**Comment by navaronbracke** [comment] 2023-11-03 14:34
It turns out that for MacOS we only have the barcode format (= the symbology). The Vision API does not have a notion of a barcode "type", like what MLKit gives us for iOS and Android. See https://developer.apple.com/documentation/vision/vnbarcodeobservation

**Comment by JulienDev** [comment] 2023-11-03 20:57
Very clear, thanks for the explanation and fast investigation ⚡️⚡️⚡️
I'll try to write a custom parser in Dart when I'll have time

**Comment by navaronbracke** [comment] 2023-11-21 18:33
Since this has to do with the fact that on MacOS, the Vision API does not give us this kind of information, I'll close this as completed for now.

@JulienDev If you manage to write a parser that could do the detection manually for MacOS, feel free to contribute it.

**Closed by navaronbracke** 2023-11-21 18:33 UTC
Labels: macos
