### ISSUE TITLE
DetectionSpeed.noDuplicates not working on Android - no barcodes detected

### ISSUE THREAD

**Issue by henning-heisenberg** [juliansteenbakker/mobile_scanner#1252] opened 2024-12-02 07:43 UTC
**Description**
When using `DetectionSpeed.noDuplicates` on Android, the scanner stops detecting any barcodes completely. Switching to `DetectionSpeed.normal` resolves the issue.

**Steps to Reproduce**
1. Create a MobileScannerController with `DetectionSpeed.noDuplicates`
```dart
controller = MobileScannerController(
  facing: CameraFacing.back,
  detectionSpeed: DetectionSpeed.noDuplicates,
);
```
2. Start scanning
3. Point camera at any barcode

**Expected Behavior**
Scanner should detect barcodes and prevent duplicate scans within a short timeframe.

**Actual Behavior**
Scanner does not detect any barcodes at all.

**Workaround**
Using `DetectionSpeed.normal` and implementing custom throttling works as expected:
```dart
controller = MobileScannerController(
  facing: CameraFacing.back,
  detectionSpeed: DetectionSpeed.normal,
);
```

**Environment**
- mobile_scanner version: 6.0.2
- Flutter version: 3.24.3

**Comment by alexodus** [comment] 2024-12-03 09:37
+1

**Comment by navaronbracke** [comment] 2024-12-05 12:46
This is a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1079

There are some issues with the no duplicates mode.

**Closed** 2024-12-05 12:46 UTC
