### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core"

### ISSUE THREAD

**Issue by bholendraofficial** [juliansteenbakker/mobile_scanner#422] opened 2022-12-13 17:09 UTC
[!] CocoaPods could not find compatible versions for pod "GTMSessionFetcher/Core":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 4.2.0, which depends on
      Firebase/Auth (= 10.3.0) was resolved to 10.3.0, which depends on
        FirebaseAuth (~> 10.3.0) was resolved to 10.3.0, which depends on
          GTMSessionFetcher/Core (< 4.0, >= 2.1)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 0.0.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 3.2.0) was resolved to 3.2.0, which depends on
        MLKitBarcodeScanning (~> 2.2.0) was resolved to 2.2.0, which depends on
          MLKitVision (~> 4.2) was resolved to 4.2.0, which depends on
            GTMSessionFetcher/Core (~> 1.1)

**Comment by juliansteenbakker** [comment] 2022-12-13 20:38
Duplicate of #335

**Closed by juliansteenbakker** 2022-12-13 20:38 UTC
