### ISSUE TITLE
The corners are not the exact values ​​to make an overlay

### ISSUE THREAD

**Issue by najBaby** [juliansteenbakker/mobile_scanner#24] opened 2022-02-23 20:03 UTC
### What
- The corners are not the exact values ​​to make an overlay. Help me

**Comment by juliansteenbakker** [comment] 2022-02-23 20:20
This is a known issue and I have already been working on it. In short, we need to lock the aspect ratio in order to match the overlay with the preview. I have already started with some implementation of this but have not finished yet.

**Comment by najBaby** [comment] 2022-02-23 21:27
Ok thanks you. I need fastly.

**Comment by WingCH** [comment] 2022-05-11 04:27
same issue!

**Comment by Mathistis** [comment] 2022-05-13 16:56
Same issue here

**Comment by WingCH** [comment] 2022-05-26 00:50
any update about this issue?
i need correct corner position to handle scan area feature

**Comment by SeriousMonk** [comment] 2022-07-07 00:14
Hi, is there a build-in way for creating an overlay? 
Another option would be to put the MobileScanner inside a Stack and manually create an overlay, but a build in one (like in qr_code_scanner) would be much nicer to use.

**Comment by blueeyestw** [comment] 2022-07-13 06:24
If anyone is only looking for an overlay UI and not a restricted scan area, just do this:

```
Stack(
              children: [
                MobileScanner(
                  allowDuplicates: false,
                  controller: controller,
                  onDetect: onDetect,
                ),
                Center(
                  child: Container(
                    width: MediaQuery.of(context).size.width * 0.6,
                    height: MediaQuery.of(context).size.width * 0.6,
                    decoration: BoxDecoration(
                      color: Colors.transparent,
                      border: Border.all(color: Colors.white38, width: 4.0),
                      borderRadius: const BorderRadius.all(Radius.circular(24.0)),
                    ),
                  ),
                ),
              ],
            ),
```

**Comment by marcov-dart** [comment] 2022-12-07 16:19
I want to display an overlay with the 4 corners highlighted like the commented out one in the example (mobile_scanner_overlay.dart).
I uncommented that example and made it more or less work with the current master in git. But I don't understand the coordinate system of the List<Offset> corners. They make no sense to me whatsoever. Does anyone know what is up with those? 
I would expect the coordinates to match the coordinate system of the image as in arguments.size from onStart. If I have that I can do the calculation on the flutter side depending on BoxFit. But right now the aspect ratio of the coordinates coming back is all off. In the horizontal direction I determined by trial and error that have to divide by 4 and in the vertical by 2.3 to make it more or less match the corners.

**Comment by marcov-dart** [comment] 2022-12-07 16:23
> This is a known issue and I have already been working on it. In short, we need to lock the aspect ratio in order to match the overlay with the preview. I have already started with some implementation of this but have not finished yet.

I am trying to understand what you are saying here, but I don't understand why you would need to lock aspect ratio? The coordinates that you get back from the detector are they not in the same coordinate system as the input image?

**Comment by juliansteenbakker** [comment] 2022-12-13 15:30
The issue is fixed by using the size of the captureOutput buffer, which is implemented in the latest beta version.

With version 3.0.0-beta.4 you can use an custom scanning area like shown in the example app: https://github.com/juliansteenbakker/mobile_scanner/blob/master/example/lib/barcode_scanner_window.dart 

Please note that this is still a beta so there can be breaking changes in the near future.

**Closed by juliansteenbakker** 2022-12-13 15:30 UTC
Labels: enhancement, in progress
