### ISSUE TITLE
Cannot round NaN excetion crushing the app

### ISSUE THREAD

**Issue by sagarehs** [juliansteenbakker/mobile_scanner#1156] opened 2024-08-20 06:20 UTC
FATAL EXCEPTION: main
Cannot round NaN

FATAL EXCEPTION: main
E/AndroidRuntime( 8980): Process: com.example.app_name, PID: 8980
E/AndroidRuntime( 8980): java.lang.IllegalArgumentException: Cannot round NaN value.
E/AndroidRuntime( 8980): at kotlin.math.MathKt__MathJVMKt.roundToInt(MathJVM.kt:1165)
E/AndroidRuntime( 8980): at dev.steenbakker.mobile_scanner.MobileScanner.isBarcodeInScanWindow(MobileScanner.kt:177)
E/AndroidRuntime( 8980): at dev.steenbakker.mobile_scanner.MobileScanner.captureOutput$lambda$6$lambda$1(MobileScanner.kt:94)
E/AndroidRuntime( 8980): at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$WHeCA6JglANxIjeKXlTGAl6H0VI(Unknown Source:0)
E/AndroidRuntime( 8980): at dev.steenbakker.mobile_scanner.MobileScanner$$ExternalSyntheticLambda3.invoke(Unknown Source:8)
E/AndroidRuntime( 8980): at dev.steenbakker.mobile_scanner.MobileScanner.captureOutput$lambda$6$lambda$2(MobileScanner.kt:80)
E/AndroidRuntime( 8980): at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$FNQbW8g2ym_6Y4EZ1gdRVqQ6VqA(Unknown Source:0)
E/AndroidRuntime( 8980): at dev.steenbakker.mobile_scanner.MobileScanner$$ExternalSyntheticLambda14.onSuccess(Unknown Source:2)
E/AndroidRuntime( 8980): at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.2:1)
E/AndroidRuntime( 8980): at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 8980): at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8980): at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime( 8980): at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime( 8980): at android.app.ActivityThread.main(ActivityThread.java:8762)
E/AndroidRuntime( 8980): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8980): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/AndroidRuntime( 8980): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
I/Process ( 8980): Sending signal. PID: 8980 SIG: 9
Lost connection to device.

**Comment by navaronbracke** [comment] 2024-08-20 06:33
Duplicate of #1134 

This was fixed in version 5.2.0

**Closed by navaronbracke** 2024-08-20 06:33 UTC

**Comment by navaronbracke** [comment] 2024-08-20 07:04
You'll have to upgrade your firebase dependencies, as those are still depending on an older version of package:web

**Comment by parthrajput0504** [comment] 2024-08-20 09:56
Because bookelibrary_flutter depends on mobile_scanner ^5.2.0 which depends on web ^1.0.0, web ^1.0.0 is required.
So, because bookelibrary_flutter depends on web ^0.5.1, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on mobile_scanner: flutter pub add mobile_scanner:^5.1.1

I have upgraded all the firebase dependencies still getting the same error


  firebase_core: ^3.3.0

  firebase_auth: ^5.1.4

  firebase_crashlytics: ^4.0.4

  firebase_analytics: ^11.2.1

  firebase_auth_web: ^5.12.5
