### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GoogleUtilities/Environment"

### ISSUE THREAD

**Issue by Zambiorix** [juliansteenbakker/mobile_scanner#1181] opened 2024-09-18 14:27 UTC
Hello all,

I looking for a way for `mobile_scanner` and `firebase` to play nice with eachother.
I've seen an earlier issue but with another pod, so I'm not sure it's related.

My project with `mobile_scanner` was running just fine until I added firebase (want to use messaging).
Removing `mobile_scanner` made it run again, so I'm sure their dependencies are conflicting.

I'm new to flutter , so I'm not sure how to solve this ..
The recommandations didn't help anything ..

Thanks for your help
Cheers

Gerd

```
[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/Environment":
      In snapshot (Podfile.lock):
        GoogleUtilities/Environment (= 8.0.2, ~> 8.0)

      In Podfile:
        firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 3.5.0, which depends on
          Firebase/CoreOnly (= 11.0.0) was resolved to 11.0.0, which depends on
            FirebaseCore (= 11.0.0) was resolved to 11.0.0, which depends on
              GoogleUtilities/Environment (~> 8.0)

        firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 3.5.0, which depends on
          Firebase/CoreOnly (= 11.0.0) was resolved to 11.0.0, which depends on
            FirebaseCore (= 11.0.0) was resolved to 11.0.0, which depends on
              GoogleUtilities/Logger (~> 8.0) was resolved to 8.0.2, which depends on
                GoogleUtilities/Environment (= 8.0.2)

        mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
          GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
            GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
              MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
                GoogleDataTransport (< 10.0, >= 9.4.1) was resolved to 9.4.1, which depends on
                  GoogleUtilities/Environment (~> 7.7)


    You have either:
     * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
     * changed the constraints of dependency `GoogleUtilities/Environment` inside your development pod `mobile_scanner`.
       You should run `pod update GoogleUtilities/Environment` to apply changes you've made.
```

**Comment by navaronbracke** [comment] 2024-09-18 18:35
This is a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1165

Unfortunately, until there is a new MLKit version for iOS, we cannot resolve this.

**Closed by navaronbracke** 2024-09-18 18:35 UTC

**Comment by Zambiorix** [comment] 2024-09-18 19:48
I already thought so ... Hopefully that doesn't take too long.
Since I need both (fcm/apns and qr-code scanning) I need to find a workaround.

**Comment by navaronbracke** [comment] 2024-09-18 21:10
I do have plans to switch iOS to use the Vision API from Apple, which would eliminate this issue. We already use that on MacOS.

However, I still need to work on that implementation.

**Comment by Zambiorix** [comment] 2024-09-19 10:32
Great, I'll concentrate on other parts of the project first and check back later. Do you have an estimate when the switch would be finished? Are we talking about weeks or months? No rush or anything, I know people work on these projects in their spare time. It's just a friendly question to have an idea about the timeframe...
Thanks

**Comment by Zambiorix** [comment] 2024-09-19 10:33
Ha, iemand van Gent :-) ... ikzelf ben van Bornem (Klein Brabant)

**Comment by navaronbracke** [comment] 2024-09-19 10:41
@Zambiorix I'm about to fix up a small issue for the patch for the `already started` error. After that I would like to fix the NV21 format bug for Samsung A23 devices. (this is a small bug and easy to test)

I also had the Android Impeller migration planned, but since that is still in preview, I'm putting that on hold until this other work is finished.

I would love to start with this new version sometime at the end of this week, after having finished up the other two small fixes. I would call it version 6.0, since it is a potential breaking change, and will make it available as a beta version.

Unfortunately you are right that this is something I do in my spare time. But I want these bugs fixed, as they prevent our customers from using the plugin properly.

If I put some effort in it, I can definitely have this fixed in a week or so, if I have the time.

**Comment by blencm** [comment] 2024-09-21 11:39
Firebase library downgrade

`firebase_core: ^2.31.0`
`firebase_messaging: ^14.9.2`
`cloud_firestore: ^4.17.5`

Use the latest version of mobile_scanner
`mobile_scanner: ^5.2.3`
