### ISSUE TITLE
StrictMode DiskReadViolation blocking main thread

### ISSUE THREAD

**Issue by radivojeostojic** [juliansteenbakker/mobile_scanner#988] opened 2024-03-18 10:27 UTC
During testing of our Android application in StrictMode, we noticed increased number of DiskReadViolation of our MainThread related to mobile_scanner.

Sample log:

```
03-15 14:07:39.411 29151 29161 D StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
03-15 14:07:39.411 29151 29161 D StrictMode: 	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1786)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:264)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at android.view.Surface.finalize(Surface.java:216)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at java.lang.Thread.run(Thread.java:764)
03-15 14:07:39.411 29151 29161 D StrictMode: Caused by: java.lang.Throwable: Explicit termination method 'release' not called
03-15 14:07:39.411 29151 29161 D StrictMode: 	at dalvik.system.CloseGuard.open(CloseGuard.java:221)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at android.view.Surface.setNativeObjectLocked(Surface.java:618)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at android.view.Surface.<init>(Surface.java:201)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda$12$lambda$6(MobileScanner.kt:265)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$21H8rT36yebuNypNxsrOxTYXO_8(Unknown Source:0)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at dev.steenbakker.mobile_scanner.MobileScanner$$ExternalSyntheticLambda0.onSurfaceRequested(Unknown Source:4)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at androidx.camera.core.Preview.lambda$sendSurfaceRequest$1(Preview.java:516)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at androidx.camera.core.Preview$$ExternalSyntheticLambda0.run(Unknown Source:4)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at android.os.Handler.handleCallback(Handler.java:873)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at android.os.Looper.loop(Looper.java:214)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
03-15 14:07:39.411 29151 29161 D StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

second log:

03-15 14:12:40.025  7576  7586 D StrictMode: StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
03-15 14:12:40.025  7576  7586 D StrictMode: 	at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1786)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:264)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at android.view.Surface.finalize(Surface.java:216)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:250)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:237)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at java.lang.Daemons$Daemon.run(Daemons.java:103)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at java.lang.Thread.run(Thread.java:764)
03-15 14:12:40.025  7576  7586 D StrictMode: Caused by: java.lang.Throwable: Explicit termination method 'release' not called
03-15 14:12:40.025  7576  7586 D StrictMode: 	at dalvik.system.CloseGuard.open(CloseGuard.java:221)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at android.view.Surface.setNativeObjectLocked(Surface.java:618)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at android.view.Surface.<init>(Surface.java:201)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at dev.steenbakker.mobile_scanner.MobileScanner.start$lambda$12$lambda$6(MobileScanner.kt:265)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at dev.steenbakker.mobile_scanner.MobileScanner.$r8$lambda$21H8rT36yebuNypNxsrOxTYXO_8(Unknown Source:0)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at dev.steenbakker.mobile_scanner.MobileScanner$$ExternalSyntheticLambda0.onSurfaceRequested(Unknown Source:4)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at androidx.camera.core.Preview.lambda$sendSurfaceRequest$1(Preview.java:516)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at androidx.camera.core.Preview$$ExternalSyntheticLambda0.run(Unknown Source:4)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at android.os.Handler.handleCallback(Handler.java:873)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at android.os.Looper.loop(Looper.java:214)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at java.lang.reflect.Method.invoke(Native Method)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
03-15 14:12:40.025  7576  7586 D StrictMode: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)


```

Tested on multiple Android devices, current log is from the Android 12 (Samsung s8+)

Flutter doctor output:

```

[!] Flutter (Channel [user-branch], 3.16.9, on macOS 14.0 23A344 darwin-arm64, locale en-RS)
    ! Flutter version 3.16.9 on channel [user-branch] at /Users/radivojeostojic/Documents/development/flutter
      Currently on an unknown channel. Run `flutter channel` to switch to an official channel.
      If that doesn't fix the issue, reinstall Flutter by following instructions at https://flutter.dev/docs/get-started/install.
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.17.6/libexec/bin/dart, which is not inside your current Flutter SDK checkout at
      /Users/radivojeostojic/Documents/development/flutter. Consider adding /Users/radivojeostojic/Documents/development/flutter/bin to the front of your path.
    ! Upstream repository unknown source is not a standard remote.
      Set environment variable "FLUTTER_GIT_URL" to unknown source to dismiss this error.
    • Framework revision 41456452f2 (8 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/radivojeostojic/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15E204a
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] VS Code (version 1.68.1)
    • VS Code at /Users/radivojeostojic/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.60.0

[✓] Connected device (4 available)
    • SM G955U1 (mobile)         • 988bdc37395638324a                   • android-arm64  • Android 9 (API 28)
    • iPhone 15 Pro Max (mobile) • 9D762A9B-159B-4456-B8E3-99ECD5B453D0 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-2 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 14.0 23A344 darwin-arm64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 122.0.6261.129
    ! Error: Browsing on the local area network for Radivoje’s iPhone. Ensure the device is unlocked and attached with a cable or associated with the same local area
      network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

Version of the plugin that we are using is: `3.5.5`

**Comment by navaronbracke** [comment] 2024-03-19 15:07
@radivojeostojic I think I found the cause. We allocate a `BarcodeScanner` client, but we do not close it.

In terms of the CameraPreview, we do unbind all CameraX use cases, so I think that is the issue.
(The camera preview does not seem to have an explicit release method)

I will fix this issue for the next beta.

**Comment by navaronbracke** [comment] 2024-03-19 15:29
I made a preliminary fix for this, still need to test it though.

**Comment by navaronbracke** [comment] 2024-03-20 09:25
I tried to do a quick test with StrictMode enabled:

I've used Gradle 8.1.2 and modified the example app to enable strict mode:

```
// Example app MainActivity
package dev.steenbakker.mobile_scanner_example

import android.os.Bundle
import android.os.StrictMode
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        StrictMode.setThreadPolicy(
            StrictMode.ThreadPolicy.Builder()
                .detectDiskReads()
                .detectDiskWrites()
                .detectNetwork() // or .detectAll() for all detectable problems
                .penaltyLog()
                .build()
        )
        StrictMode.setVmPolicy(
            StrictMode.VmPolicy.Builder()
                .detectLeakedSqlLiteObjects()
                .detectLeakedClosableObjects()
                .penaltyLog()
                .penaltyDeath()
                .build()
        )

        super.onCreate(savedInstanceState)
    }
}
```

I did not see any `StrictMode policy violation:` errors when running with `mobile_scanner 5.0.0-beta.1` in logcat when opening the CameraPreview and then going back (which I assume _should_ release the CameraPreview and other resources)

Could you provide a minimal reproduction, using the example app, with changes to the MainActivity to enable Strict Mode ?

**Comment by navaronbracke** [comment] 2024-04-16 13:09
@radivojeostojic Did you get some time to re-evaluate if https://github.com/juliansteenbakker/mobile_scanner/pull/991 fixes the problem you are seeing?

**Comment by navaronbracke** [comment] 2024-06-17 15:18
This might also indicate why we get the `A resource failed to call release.` warnings when the camera is disposed. This is probably an indication of the problem.

**Closed** 2024-08-08 11:33 UTC
Labels: bug, android
