### ISSUE TITLE
PlatformException (PlatformException(MobileScanner, Called start() while already started, null, null))

### ISSUE THREAD

**Issue by gusanumatthew** [juliansteenbakker/mobile_scanner#1076] opened 2024-05-26 11:44 UTC
I am unable to use the mobile scanner package. 
The camera is started successfully on the first try. The moment you hot restart your app, you get the error 
PlatformException (PlatformException(MobileScanner, Called start() while already started, null, null))

Version: 5.1.1
Flutter version: 3.22.1

**Comment by tperraut** [comment] 2024-05-27 16:18
Same issue here

**Comment by navaronbracke** [comment] 2024-05-28 06:17
This is a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/773

We indeed need to fix our support for hot restart and work is ongoing to address this.

**Closed by navaronbracke** 2024-05-28 06:17 UTC
