### ISSUE TITLE
MissingPluginException(No implementation found for method listen on channel dev.steenbakker.mobile_scanner/scanner/event)

### ISSUE THREAD

**Issue by MapperMalte** [juliansteenbakker/mobile_scanner#74] opened 2022-03-19 03:22 UTC
When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:506:9)
<asynchronous suspension>

**Comment by juliansteenbakker** [comment] 2022-03-19 07:42
On which platform are you having this issue? What where you doing, just starting the app or scanning a barcode?

**Comment by EricRode** [comment] 2022-03-20 18:08
I have the same issue. I am using the web platform. The error occurs after starting the scanner, closing the scanner, and then on the next start of the scanner.

**Comment by EricRode** [comment] 2022-03-20 18:09
![error](https://user-images.githubusercontent.com/73781513/159176327-829e5e96-1f75-472c-8a4f-c84d1209b5df.png)
Here is the stacktrace

**Comment by juliansteenbakker** [comment] 2022-04-01 10:09
Duplicate of #64

**Closed by juliansteenbakker** 2022-04-01 10:09 UTC
Labels: bug, web
