### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GoogleDataTransport"

### ISSUE THREAD

**Issue by KalybosPro** [juliansteenbakker/mobile_scanner#1200] opened 2024-10-03 20:08 UTC
[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.3, which depends on
      Firebase/Messaging (= 11.2.0) was resolved to 11.2.0, which depends on
        FirebaseMessaging (~> 11.2.0) was resolved to 11.2.0, which depends on
          GoogleDataTransport (~> 10.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1)

**Comment by alunmvs** [comment] 2024-10-04 03:56
Same case happen on my projects

**Comment by aazgersky** [comment] 2024-10-04 07:32
Faced with same problem

**Comment by yeras-is** [comment] 2024-10-04 08:19
Same

**Comment by Mr-Nadyar** [comment] 2024-10-04 11:30
i get same

**Comment by yeras-is** [comment] 2024-10-04 11:32
Ducplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1182

**Comment by navaronbracke** [comment] 2024-10-05 07:57
This is a duplicate of #1182

**Closed by navaronbracke** 2024-10-05 07:57 UTC
