### ISSUE TITLE
failed build podfile ios : CocoaPods could not find compatible versions for pod "GoogleDataTransport"

### ISSUE THREAD

**Issue by ferisetyo1** [juliansteenbakker/mobile_scanner#1182] opened 2024-09-19 06:44 UTC
pub dev dependecies :
firebase_analytics: ^11.2.0
firebase_core: ^3.2.0
firebase_messaging: ^15.0.3
firebase_crashlytics: ^4.0.3
firebase_in_app_messaging: ^0.8.0+3
mobile_scanner: ^5.2.3

-------------

```
Analyzing dependencies
firebase_analytics: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
firebase_in_app_messaging: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.0, which depends on
      Firebase/Messaging (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseMessaging (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleDataTransport (~> 10.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1)
```

**Comment by Dkkathiriya** [comment] 2024-09-19 08:05
I have also same error

`Analyzing dependencies
cloud_firestore: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.0.0, which depends on
      Firebase/Messaging (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseMessaging (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleDataTransport (~> 10.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1)
`

**Comment by Mortando** [comment] 2024-09-19 08:09
Same .... GoogleDataTransport must be > 10.0

Temporary solution is to downgrade firebase_core from ^3 to ^2.32.0 and match all other firebase dependencies...

**Comment by DevUser611** [comment] 2024-09-19 16:11
`[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/UserDefaults":
      In snapshot (Podfile.lock):
        GoogleUtilities/UserDefaults (= 8.0.2, ~> 8.0)

      In Podfile:
        firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.2, which depends on
`

almost same here

**Comment by DevUser611** [comment] 2024-09-19 16:15
mostly same issue but other tool "GoogleUtilities/UserDefaults (= 8.0.2, ~> 8.0)"

`

[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/UserDefaults":
      In snapshot (Podfile.lock):
        GoogleUtilities/UserDefaults (= 8.0.2, ~> 8.0)

      In Podfile:
        firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.2, which depends on
          Firebase/Messaging (= 11.0.0) was resolved to 11.0.0, which depends on
            FirebaseMessaging (~> 11.0.0) was resolved to 11.0.0, which depends on
              GoogleUtilities/UserDefaults (~> 8.0)

        mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
          GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
            MLKitBarcodeScanning (~> 5.0.0) was resolved to 5.0.0, which depends on
              MLKitCommon (~> 11.0) was resolved to 11.0.0, which depends on
                GoogleUtilities/UserDefaults (< 8.0, >= 7.13.0)

`

**Comment by tegaologe** [comment] 2024-09-19 17:20
I have the exact same problem.. is there any solution?

**Comment by lukasnevosad** [comment] 2024-09-19 17:29
Including mine since it goes one step deeper in the stack:

```
[!] CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 11.3.0, which depends on
      Firebase/Analytics (= 11.0.0) was resolved to 11.0.0, which depends on
        Firebase/Core (= 11.0.0) was resolved to 11.0.0, which depends on
          FirebaseAnalytics (~> 11.0.0) was resolved to 11.0.0, which depends on
            nanopb (~> 3.30910.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1) was resolved to 9.4.1, which depends on
              nanopb (< 2.30911.0, >= 2.30908.0)
```

**Comment by adrolter** [comment] 2024-09-19 21:35
+1

**Comment by pierfani** [comment] 2024-09-19 21:51
[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/UserDefaults":
  In Podfile:
    firebase_app_check (from `.symlinks/plugins/firebase_app_check/ios`) was resolved to 0.3.1-2, which depends on
      FirebaseAppCheck (~> 11.0.0) was resolved to 11.0.0, which depends on
        GoogleUtilities/UserDefaults (~> 8.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleUtilities/UserDefaults (< 8.0, >= 7.13.0)

**Comment by anchao-lu** [comment] 2024-09-20 02:03
+1

**Comment by Lazizbek97** [comment] 2024-09-20 05:01
any news?

`[!] CocoaPods could not find compatible versions for pod "GoogleUtilities/Environment":
  In Podfile:
    firebase_remote_config (from `.symlinks/plugins/firebase_remote_config/ios`) was resolved to 5.1.2, which depends on
      Firebase/RemoteConfig (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseRemoteConfig (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleUtilities/Environment (~> 8.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.3, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1) was resolved to 9.4.1, which depends on
              GoogleUtilities/Environment (~> 7.7)`

**Comment by Mortando** [comment] 2024-09-20 05:04
ML Kit must be first updated, issue tracker: https://issuetracker.google.com/issues/362452861

It's just been reassigned internally at google yesterday...

Downgrade firebase_core to 2.32.0 and the rest matching ... this might take a while

**Comment by LipuBeingeniere** [comment] 2024-09-20 07:44
+1

**Comment by lukasnevosad** [comment] 2024-09-20 09:10
@Mortando Thank you for linking the issue, I confirm downgrading works.

The correct Flutter dependency is
```
firebase_core: 3.3.0
```
(Note the missing `^`)

Then the usual and I was able to build:
```
rm podfile.lock
pod install --repo-update
```

**Comment by anchao-lu** [comment] 2024-09-21 03:39
[Firebase has problems in Xcode16 iOS18](https://github.com/firebase/flutterfire/issues/13323). So we have to upgrade firebase.

**Comment by navaronbracke** [comment] 2024-09-23 11:23
This is a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1165

Unfortunately, MLKit also depends on GoogleDataTransport, and there is no new release for MLKit just yet.

**Closed by navaronbracke** 2024-09-23 11:23 UTC

**Comment by pvc97** [comment] 2024-09-27 03:09
Same issue

**Comment by myFLO-Developer1** [comment] 2024-09-29 22:29
+1

**Comment by bluegene37** [comment] 2024-09-29 22:30
+1

**Comment by kalyujniy** [comment] 2024-10-01 12:48
+1

**Comment by StatTark** [comment] 2024-10-03 18:40
+1

**Comment by malte1989** [comment] 2024-10-04 15:21
With MacOs Sequoia 15 I can not downgrade. It won't work for iOS.
Google is currently not seeming to update the [GoogleMLKit/BarcodeScanning](https://issuetracker.google.com/u/1/issues/362452861?pli=1).

Is there any possibility so switch to different scanning library (for iOS)?

**Comment by adrolter** [comment] 2024-10-04 15:52
@malte1989 See [this comment](https://github.com/juliansteenbakker/mobile_scanner/issues/1165#issuecomment-2371608445)

**Comment by malte1989** [comment] 2024-10-08 17:31
It is fixed: 
https://pub.dev/packages/mobile_scanner in version 6.0.0

flutter clean && flutter pub get
pod repo update
flutter build ipa

**Comment by HarshitaRawat1** [comment] 2024-10-11 09:32
Change dependencies to these versions: 

  firebase_messaging: ^14.9.2
  firebase_core: ^2.31.0
  mobile_scanner: ^5.2.3
  
  It will work.
