### ISSUE TITLE
App crashes sometimes when launched scanner screen.

### ISSUE THREAD

**Issue by ramlaxmangroup** [juliansteenbakker/mobile_scanner#1137] opened 2024-08-01 05:15 UTC
I have a recent stack trace in a below screenshot file.

![WhatsApp Image 2024-08-01 at 10 06 56_9ac76557](https://github.com/user-attachments/assets/5a04b167-2b72-4c8f-a78f-a8dd6a6f10e5)

**Comment by navaronbracke** [comment] 2024-08-01 06:08
This is a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1134 which was reported 2 days ago.

I'm going to close this issue in favor of that one.

**Closed by navaronbracke** 2024-08-01 06:08 UTC
