### ISSUE TITLE
CocoaPods could not find compatible versions for pod "GoogleDataTransport"

### ISSUE THREAD

**Issue by LinschotenMelle** [juliansteenbakker/mobile_scanner#1171] opened 2024-09-05 08:42 UTC
I encountered an issue while resolving dependencies in my Podfile related to the pod GoogleDataTransport. The error message indicates version conflicts, particularly with the following dependencies:

- firebase_performance:
Version resolved: `0.10.0-5`
FirebasePerformance depends on GoogleDataTransport (~> 10.0)

- mobile_scanner:
Version resolved: `5.2.1`
Depends on GoogleMLKit/BarcodeScanning (~> 6.0.0), which in turn depends on MLKitBarcodeScanning (~> 5.0.0)
MLKitCommon was resolved to version 11.0.0 but also depends on GoogleDataTransport (< 10.0, >= 9.4.1)
It seems that there is a conflict between the required versions of GoogleDataTransport between Firebase Performance and MLKit dependencies.

Steps to reproduce:

Include the following dependencies in the Podfile:
* firebase_performance
* mobile_scanner

Run pod install
Observe the error related to incompatible versions of GoogleDataTransport
Expected behavior: Dependencies should resolve without any version conflict.

**To resolve this issue**, it would be beneficial for the maintainers of the mobile_scanner package to update their dependency on GoogleDataTransport to support the latest version, which is currently required by Firebase Performance. Updating to GoogleDataTransport (~> 10.0) could resolve the conflict and allow both libraries to coexist without versioning issues.

![2024-09-05 10_14_26-MacMini (Mac’s Mac mini) - VNC Viewer](https://github.com/user-attachments/assets/4404c1c7-3b05-4000-82cc-7e0384c098bc)

**Comment by navaronbracke** [comment] 2024-09-05 12:05
This is a duplicate of https://github.com/juliansteenbakker/mobile_scanner/issues/1165

Before opening duplicate issues, please search in the open issues to see if your issue is already listed.

**Closed by navaronbracke** 2024-09-05 12:05 UTC
